import AppKit
import ApplicationServices
import Carbon.HIToolbox

/// Puts text where the caret is: pasteboard + synthetic ⌘V, then the old clipboard comes back.
@MainActor
enum TextInserter {
    enum Outcome {
        case pasted
        /// No Accessibility access: the text is left on the clipboard for the user to paste.
        case copiedOnly
    }

    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static func insert(_ text: String, smartSpacing: Bool, restoreClipboard: Bool) async -> Outcome {
        let pasteboard = NSPasteboard.general
        guard AXIsProcessTrusted() else {
            pasteboard.clearContents()
            pasteboard.setString(text, forType: .string)
            return .copiedOnly
        }

        var text = text
        if smartSpacing, await needsLeadingSpace(before: text) { text = " " + text }

        let saved = restoreClipboard ? snapshot(pasteboard) : nil
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: transientType)
        item.setData(Data(), forType: autoGeneratedType)
        pasteboard.writeObjects([item])
        let ours = pasteboard.changeCount

        postPaste()

        if let saved {
            // Give the target app time to read the pasteboard before putting the user's clipboard back.
            try? await Task.sleep(for: .milliseconds(450))
            if pasteboard.changeCount == ours {
                pasteboard.clearContents()
                if !saved.isEmpty { pasteboard.writeObjects(saved) }
            }
        }
        return .pasted
    }

    private static func snapshot(_ pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { original in
            let copy = NSPasteboardItem()
            for type in original.types {
                if let data = original.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }

    private static func postPaste() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let key = CGKeyCode(pasteKeyCode())
        let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cgAnnotatedSessionEventTap)
        up?.post(tap: .cgAnnotatedSessionEventTap)
    }

    /// The key that types "v" in the current ASCII-capable layout (so ⌘V also works on Dvorak & co).
    private static func pasteKeyCode() -> Int {
        guard let source = TISCopyCurrentASCIICapableKeyboardLayoutInputSource()?.takeRetainedValue(),
            let pointer = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData)
        else { return kVK_ANSI_V }
        let data = Unmanaged<CFData>.fromOpaque(pointer).takeUnretainedValue() as Data
        return data.withUnsafeBytes { raw -> Int in
            guard let layout = raw.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else { return kVK_ANSI_V }
            for code in 0 ..< 128 {
                var deadKeys: UInt32 = 0
                var length = 0
                var characters = [UniChar](repeating: 0, count: 4)
                let status = UCKeyTranslate(
                    layout, UInt16(code), UInt16(kUCKeyActionDown), 0, UInt32(LMGetKbdType()),
                    OptionBits(kUCKeyTranslateNoDeadKeysBit), &deadKeys, characters.count, &length, &characters)
                if status == noErr, length == 1, characters[0] == UniChar(("v" as Unicode.Scalar).value) {
                    return code
                }
            }
            return kVK_ANSI_V
        }
    }

    /// Whether the character before the caret calls for a space in front of the dictated text.
    private static func needsLeadingSpace(before text: String) async -> Bool {
        guard let first = text.first, !",.;:!?)]}…%".contains(first) else { return false }
        let previous = await Task.detached(priority: .userInitiated) { characterBeforeCaret() }.value
        guard let previous else { return false }
        return !(previous.isWhitespace || "([{«„\"'“‘/-".contains(previous))
    }

    nonisolated private static func characterBeforeCaret() -> Character? {
        let system = AXUIElementCreateSystemWide()
        AXUIElementSetMessagingTimeout(system, 0.1)
        var focused: CFTypeRef?
        guard AXUIElementCopyAttributeValue(system, kAXFocusedUIElementAttribute as CFString, &focused) == .success,
            let focused, CFGetTypeID(focused) == AXUIElementGetTypeID()
        else { return nil }
        let element = focused as! AXUIElement

        var rangeValue: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, &rangeValue) == .success,
            let rangeValue, CFGetTypeID(rangeValue) == AXValueGetTypeID()
        else { return nil }
        var selection = CFRange()
        guard AXValueGetValue(rangeValue as! AXValue, .cfRange, &selection), selection.location > 0 else { return nil }

        var previous = CFRange(location: selection.location - 1, length: 1)
        guard let parameter = AXValueCreate(.cfRange, &previous) else { return nil }
        var string: CFTypeRef?
        guard AXUIElementCopyParameterizedAttributeValue(
            element, kAXStringForRangeParameterizedAttribute as CFString, parameter, &string) == .success
        else { return nil }
        return (string as? String)?.last
    }
}
